gaarf:
  output: bq
  bq:
    project: YOUR-BQ-PROJECT
    dataset: urp
  # Do not change API version manually
  api_version: 10
  account: 'MCC-ID'
  params:
    macro:
      start_date: ":YYYYMMDD-120"
      end_date: ":YYYYMMDD-1"
gaarf-bq:
  project: YOUR-BQ-PROJECT
  params:
    macro:
      bq_dataset: urp
      output_dataset: urp_output
      target_dataset: urp_target
      legacy_dataset: urp_legacy
    template:
      cohort_days: 0,1,3,5,7,14,30
